apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cm2http-read
  labels:
    app: cm2http
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
  resourceNames:
    - "kube-root-ca.crt"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm2http-read-crb
  labels:
    app: cm2http
roleRef:
  kind: ClusterRole
  name: cm2http-read
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cm2http
  namespace: cm2http-system