kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm2http-role
  labels:
    app: cm2http
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm2http-rb
  labels:
    app: cm2http
roleRef:
  kind: Role
  name: cm2http-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cm2http